import {
    FiActivity,
    FiAirplay,
    FiAlertCircle,
    FiAlertOctagon,
    FiAlertTriangle,
    FiArchive,
    FiBell,
    FiBookmark,
    FiBox,
    FiBriefcase,
    FiCalendar,
    FiCheckCircle,
    FiChevronDown,
    FiChevronLeft,
    FiChevronRight,
    FiChevronsLeft,
    FiChevronsRight,
    FiClipboard,
    FiClock,
    FiCreditCard,
    FiDatabase,
    FiDollarSign,
    FiEdit,
    FiEye,
    FiFile,
    FiFileText,
    FiFilter,
    FiFlag,
    FiFolder,
    FiGrid,
    FiHeart,
    FiHome,
    FiInbox,
    FiInfo,
    FiLayers,
    FiList,
    FiLock,
    FiMail,
    FiMap,
    FiMapPin,
    FiMenu,
    FiMessageCircle,
    FiMessageSquare,
    FiMoon,
    FiMoreHorizontal,
    FiMoreVertical,
    FiPackage,
    FiPhone,
    FiPieChart,
    FiPlus,
    FiPrinter,
    FiSave,
    FiSearch,
    FiSettings,
    FiShield,
    FiShoppingBag,
    FiShoppingCart,
    FiStar,
    FiSun,
    FiTrash2,
    FiTrello,
    FiTruck,
    FiUser,
    FiUsers,
    FiX,
} from 'react-icons/fi';

// Dashboard Icons
export const DashboardIcons = {
    // Navigation
    Home: FiHome,
    Menu: FiMenu,
    ChevronLeft: FiChevronLeft,
    ChevronRight: FiChevronRight,
    ChevronsLeft: FiChevronsLeft,
    ChevronsRight: FiChevronsRight,
    
    // Actions
    Add: FiPlus,
    Edit: FiEdit,
    Delete: FiTrash2,
    Close: FiX,
    Search: FiSearch,
    Filter: FiFilter,
    More: FiMoreHorizontal,
    MoreVertical: FiMoreVertical,
    Save: FiSave,
    
    // UI Elements
    Settings: FiSettings,
    Bell: FiBell,
    Sun: FiSun,
    Moon: FiMoon,
    
    // Data & Content
    List: FiList,
    Grid: FiGrid,
    Table: FiTrello,
    File: FiFile,
    FileText: FiFileText,
    Folder: FiFolder,
    
    // User Related
    User: FiUser,
    Users: FiUsers,
    Lock: FiLock,
    Mail: FiMail,
    Phone: FiPhone,
    Shield: FiShield,
    
    // Business & Commerce
    Cart: FiShoppingCart,
    Bag: FiShoppingBag,
    Package: FiPackage,
    Truck: FiTruck,
    CreditCard: FiCreditCard,
    Dollar: FiDollarSign,
    
    // Status & Notifications
    Success: FiCheckCircle,
    Info: FiInfo,
    Warning: FiAlertTriangle,
    Error: FiAlertOctagon,
    Alert: FiAlertCircle,
    
    // Misc
    Activity: FiActivity,
    Calendar: FiCalendar,
    Clock: FiClock,
    Star: FiStar,
    Heart: FiHeart,
    Bookmark: FiBookmark,
    Flag: FiFlag,
    Map: FiMap,
    MapPin: FiMapPin,
    Layers: FiLayers,
    Database: FiDatabase,
    Chart: FiPieChart,
    Printer: FiPrinter,
    Briefcase: FiBriefcase,
    Box: FiBox,
    Archive: FiArchive,
    Inbox: FiInbox,
    Message: FiMessageCircle,
    MessageSquare: FiMessageSquare,
    Display: FiAirplay,
};

export default DashboardIcons; 